# Homebrew formulae
brew "git"
brew "gh"
brew "jq"
brew "nvm"
brew "pyenv"
brew "goenv"
brew "wget"

# GUI applications (1password, iterm2, google-chrome installed in install/setup.zsh)

cask "1password-cli"
cask "cursor"
cask "docker-desktop"

# Dotfiles tooling
brew "stow"
